fixed hard-coded paths
also added return value testing to the scripts

diff --git a/tests/batchrun b/tests/batchrun
--- a/tests/batchrun
+++ b/tests/batchrun
@@ -17,19 +17,24 @@ for f in `ls Reference/*.reference | sort`; do
 		expected='UNDEFINED'
 	fi
     ./retcatch.sh -c $CONFIG $outfile &> .out
-	rc=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' .out`
-    if [ $rc = $expected ]; then
-      echo -e " OK     $outfile"
-    else
-      echo
-      echo -e " FAIL   $outfile"
-      echo    "        - expected: ($expected)"
-      echo    "        - returned: ($rc)"
-      echo
-      if [ "$verbose" = "1" ]; then
-        cat .out
-      fi
-    fi
+	if [ $? -eq 0 ]; then
+	  rc=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' .out`
+      if [ $rc = $expected ]; then
+        echo -e " OK     $outfile"
+      else
+        echo
+        echo -e " FAIL   $outfile"
+        echo    "        - expected: ($expected)"
+        echo    "        - returned: ($rc)"
+        echo
+        if [ "$verbose" = "1" ]; then
+          cat .out
+        fi
+	  fi
+	else
+      echo ERROR: retcatch.sh failed with:
+	  cat .out
+	fi
     rm -f .out
   else
     echo "not found: $outfile"
diff --git a/tests/singlerun b/tests/singlerun
--- a/tests/singlerun
+++ b/tests/singlerun
@@ -12,16 +12,21 @@ for outfile in `echo $* | sed 's/ /\n/g' | sort`; do
 		expected='UNDEFINED'
 	fi
     ./retcatch.sh -c $CONFIG $outfile &> .out
-	rc=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' .out`
-    if [ $rc = $expected ]; then
-      echo -e " OK     $outfile"
-    else
-      echo
-      echo -e " FAIL   $outfile"
-      echo    "        - expected: ($expected)"
-      echo    "        - returned: ($rc)"
-      echo
-    fi
+	if [ $? -eq 0 ]; then
+	  rc=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' .out`
+      if [ $rc = $expected ]; then
+        echo -e " OK     $outfile"
+      else
+        echo
+        echo -e " FAIL   $outfile"
+        echo    "        - expected: ($expected)"
+        echo    "        - returned: ($rc)"
+        echo
+      fi
+	else
+      echo ERROR: retcatch.sh failed with:
+	  cat .out
+	fi
     rm -f .out
   else
     echo "not found: $outfile"
